version: '3.8'

services:
  web:
    image: sknezu/hive-monitor-bootstrap:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - monitor

  nginx:
    image: nginx:latest
    restart: unless-stopped 
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - grafana
      - prometheus
    networks:
      - monitor

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped    
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://localhost:80/prometheus/'
    depends_on:
      - web
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ENABLE_GZIP=true
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    depends_on:
      - prometheus
    networks:
      - monitor

networks:
  monitor:

volumes:
  grafana_storage: {}
