version: '3.8'

services:
  web:
    image: sknezu/hive-monitor:latest
    ports:
      - "5000:5000"
    networks:
      - monitor

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - web
#    networks:
#      - monitor

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - web
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards/hive-dashboard.json:/var/lib/grafana/dashboards/hive-dashboard.json
      - ./grafana/provisioning/dashboards/dashboards.yaml:/var/lib/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/provisioning/datasources/datasources.yaml:/var/lib/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus
    networks:
      - monitor

networks:
  monitor:
