name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'  # build on any change in app folder, safer than just app.py
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-buildx-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-docker-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/hive-monitor-bootstrap:latest
          ${{ secrets.DOCKER_USERNAME }}/hive-monitor-bootstrap:${{ github.sha }}

    - name: Verify Docker buildx version
      run: docker buildx version
