name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (you can change this to your preferred branch)
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./app  # Set the context to the /app folder (the folder containing the Dockerfile)
        file: ./app/Dockerfile  # Specify the path to the Dockerfile inside /app
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hive-app:0.5.0

    - name: Logout from Docker Hub
      run: docker logout
